import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Button from "@mui/material/Button";
import { useRouter } from "next/router";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <Link href="/">
              By{" "}
              <Image
                src="/logo.png"
                alt="logo"
                className={styles.vercelLogo}
                width={150}
                height={150}
                priority
              />
            </Link>
          </div>
          <p>Welcome to Tami&apos;s website</p>
        </div>

        <div className={styles.center}>
          <Link href="/join">
            <Button variant="contained" sx={{ backgroundColor: "#94B49F"}}>
              Join
            </Button>
          </Link>

          <div className={styles.thirteen}>
            <Link href="/login">
              <Button variant="contained" sx={{ backgroundColor: "#94B49F" }}>
                Login
              </Button>
            </Link>
          </div>
        </div>

        <div>
          <p>tami</p>
        </div>
      </main>
    </>
  );
}
